
class ConfigLight():
    arch='image_segmentation_icnet.libs.models.ICNet'
    aspect_ratio=2.0
    batchSize=1
    cache_filelist_read=False
    cache_filelist_write=False
    checkpoints_dir='models'
    contain_dontcare_label=False
    crop_size=512
    dataroot='./results/temp'
    dataset_mode='cityscapes'
    demo_folder='./sample_images'
    display_winsize=512
    dist_url='tcp://10.1.72.171:8000'
    gpu=0
    how_many=1000
    idx_server=0
    init_type='xavier'
    init_variance=0.02
    isTrain=False
    label_nc=35
    load_from_opt_file=False
    load_size=512
    max_dataset_size=9223372036854775807
    model='pix2pix'
    mpdist=False
    nThreads=0
    name='image-synthesis'
    nef=16
    netG='condconv'
    ngf=64
    ngpus_per_node=8
    no_flip=True
    no_instance=False
    no_pairing_check=False
    no_segmentation=False
    norm_D='spectralinstance'
    norm_E='spectralinstance'
    norm_G='spectralsync_batch'
    num_servers=1
    output_nc=3
    phase='test'
    preprocess_mode='fixed'
    results_dir='./results/'
    semantic_nc=36
    serial_batches=True
    snapshot='models/image-segmentation/icnet_final.pth'
    use_vae=True
    which_epoch='latest'
    z_dim=256
    
    #needed by spade resynth
    def __init__(self, use_spade=False):
        if use_spade:
            self.num_upsampling_layers='more'  #more, normal  
            self.gpu_ids=[0]
            self.norm_G='spectralspadesyncbatch3x3'
            use_vae=False
            name='image-synthesis_spade'
            netG='spade' #spade or pix2pixhd or condconv
